// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TopTwitchClipBotModel;

namespace TopTwitchClipBotModel.Migrations
{
    [DbContext(typeof(TopTwitchClipBotContext))]
    [Migration("20190304234636_InitialAdd")]
    partial class InitialAdd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TopTwitchClipBotModel.ChannelConfig", b =>
                {
                    b.Property<decimal>("ChannelId");

                    b.Property<int?>("MaxPostingHour");

                    b.Property<int?>("MinPostingHour");

                    b.Property<string>("Prefix");

                    b.HasKey("ChannelId");

                    b.ToTable("ChannelConfig");
                });

            modelBuilder.Entity("TopTwitchClipBotModel.ChannelTopClipConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Broadcaster");

                    b.Property<decimal>("ChannelId");

                    b.Property<int?>("NumberOfClipsPerDay");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("ChannelTopClipConfig");
                });

            modelBuilder.Entity("TopTwitchClipBotModel.TopClipHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("ChannelId");

                    b.Property<int?>("ChannelTopClipConfigId");

                    b.Property<string>("ClipUrl");

                    b.Property<string>("Slug");

                    b.Property<DateTime>("Stamp");

                    b.HasKey("Id");

                    b.HasIndex("ChannelTopClipConfigId");

                    b.ToTable("TopClipHistory");
                });

            modelBuilder.Entity("TopTwitchClipBotModel.ChannelTopClipConfig", b =>
                {
                    b.HasOne("TopTwitchClipBotModel.ChannelConfig", "ChannelConfig")
                        .WithMany("ChannelTopClipConfigs")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TopTwitchClipBotModel.TopClipHistory", b =>
                {
                    b.HasOne("TopTwitchClipBotModel.ChannelTopClipConfig", "ChannelTopClipConfig")
                        .WithMany("TopClipHistories")
                        .HasForeignKey("ChannelTopClipConfigId");
                });
#pragma warning restore 612, 618
        }
    }
}
